### ISSUE TITLE
Game crash when opening treasure chests. Weirdly, the gold key chests aren't affected by this crash...

### ISSUE THREAD

**Issue by SomeGDPerson123** [CattoDev/Gambling-mod#5]
Self explanatory

**Comment by CattoDev** [comment]
Could you please provide a crash log?

**Comment by SomeGDPerson123** [comment]
2024-12-15T07:51:17-0800
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "thesillydoggo.qolmod" mod. Please submit this crash report to its developers (TheSillyDoggo) for assistance.

== Geode Information ==
Loader Version: v4.1.0
Loader Commit: 695f39f
Bindings Commit: 16df0dd
Installed mods: 95
Outdated mods: 12
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\thesillydoggo.qolmod\thesillydoggo.qolmod.dll
Faulty Mod: QOLMod v1.7.6 (thesillydoggo.qolmod)
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00007FFB38C7E9E0 (thesillydoggo.qolmod.dll + 6e9e0)
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\thesillydoggo.qolmod\thesillydoggo.qolmod.dll + 6e9e0
 - 00000174F1777482 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 597cf (cocos2d::CCMenuItem::activate + 47)
 - 00000174EE340882 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 3cfd5 (geode::modifier::AsStaticFunction_activate<hook7<(anonymous namespace)::hook7Parent>,void (hook7<(anonymous namespace)::hook7Parent>::*)()>::Impl<void (hook7<(anonymous namespace)::hook7Parent>::*)()>::function + 21 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCMenuItem.hpp:35)
 - 00000174EE340882 (Hook handler)
 - 00000174EE37A482 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\alphalaneous.happy_textures\alphalaneous.happy_textures.dll + 8afa1
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\alphalaneous.happy_textures\alphalaneous.happy_textures.dll + 5cb9b
 - 00000174EE37A482 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 58798 (cocos2d::CCMenu::ccTouchEnded + 40)
 - 00000174EE340C82 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 3d69f (geode::modifier::AsStaticFunction_ccTouchEnded<hook15<(anonymous namespace)::hook15Parent>,void (hook15<(anonymous namespace)::hook15Parent>::*)(cocos2d::CCTouch *, cocos2d::CCEvent *)>::Impl<void (hook15<(anonymous namespace)::hook15Parent>::*)(cocos2d::CCTouch *, cocos2d::CCEvent *)>::function + 47 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCMenu.hpp:105)
 - 00000174EE340C82 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + b0f2c (cocos2d::CCTouchDispatcher::touches + 444)
 - 00000174F1773882 (Hook handler)
 - 00000174F1773882 (Hook handler)
 - 00000174F1773882 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 6b131 (cocos2d::CCEGLViewProtocol::handleTouchesEnd + 97)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 76249 (cocos2d::CCEGLView::onGLFWMouseCallBack + 345)
 - 00000174816F8C8B (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\spaghettdev.betterinputs\spaghettdev.betterinputs.dll + fdd4
 - 00000174816F8C8B (Hook handler)
 - 00000174816F8C8B (Hook handler)
 - 00000174816F8C8B (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 76286
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + d6c1b
 - C:\WINDOWS\System32\USER32.dll + 15801
 - C:\WINDOWS\System32\USER32.dll + 152dc (CallWindowProcW + 364)
 - C:\WINDOWS\SYSTEM32\OPENGL32.dll + bcf3
 - C:\WINDOWS\System32\USER32.dll + 15801
 - C:\WINDOWS\System32\USER32.dll + 1334d
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + d4548
 - 00000174818F6C82 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\syzzi.click_between_frames\syzzi.click_between_frames.dll + d15c
 - 00000174818F6C82 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 72c16 (cocos2d::CCApplication::run + 1078)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4b6e32
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 24359d (gdMainHook + 557 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:181)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4b821a
 - C:\WINDOWS\System32\KERNEL32.DLL + 2e8d7 (BaseThreadInitThunk + 23)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + dfbcc (RtlUserThreadStart + 44)

== Register States ==
RAX: 000000004d43433a
RBX: 0000000000000000
RCX: 00000174c8f0c548
RDX: 000000116e8fde98
RBP: 0000000000000000
RSP: 000000116e8fff00
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ffbd593fbcc
R8:  0000000000000001
R9:  00007ffbb7300544
R10: 00007ffbb72f0000
R11: 000000116e8fdd10
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
  | [v1.0.8] absolllute.installer
  | [v8.0.6-alpha.1] absolllute.megahack
* | [v0.3.3-alpha] alk.allium
x | [v1.0.7] alphalaneous.awesome_modifier_icons
x | [v1.0.8] alphalaneous.editortab_api
x | [v1.7.0] alphalaneous.happy_textures
x | [v1.1.6] alphalaneous.hide
x | [v1.0.9] alphalaneous.improved_group_view
x | [v1.0.12] alphalaneous.improvedlink
x | [v1.0.2] alphalaneous.old_color_triggers
x | [v1.3.3] alphalaneous.pages_api
x | [v1.2.11] alphalaneous.projectedstars
x | [v1.0.2] alphalaneous.rainbow_checkpoints
x | [v1.1.11] alphalaneous.random_tab
x | [v1.0.2] alphalaneous.settings_everywhere
x | [v1.3.0] alphalaneous_raydeeux.changefont19
* | [v1.0.0] bitz.fakegdmod
* | [v1.0.5] bitz.moregames
x | [v1.2.6] blueblock6.cleanstartpos
x | [v1.0.2] capeling.garage-stats-menu
x | [v1.0.3] cattodev.gambling
x | [v1.0.8] cdc.level_thumbnails
x | [v4.3.1] cvolton.betterinfo
x | [v1.1.0] cvolton.level-id-api
x | [v1.3.1] cvolton.misc_bugfixes
x | [v1.7.2] dankmeme.globed2
* | [v1.0.5] deaen.level-pins
x | [v1.0.11] firee.goldenbest
x | [v1.4.4] firee.object-workshop
x | [v1.1.2] firee.overchargedlevels
x | [v1.0.0-alpha.1] flafy.showcase
x | [v3.0.1] fleym.nongd
x | [v1.4.0-beta.5] gdutilsdevs.gdutils
x | [v1.10.1] geode.custom-keybinds
x | [v4.1.0] geode.loader
x | [v1.18.0] geode.node-ids
x | [v1.6.7] geode.texture-loader
x | [v1.3.1] grian.art_importer
x | [v1.1.2] hiimjustin000.better_safe
x | [v1.0.3] hiimjustin000.developer_badges
x | [v1.4.10] hiimjustin000.fake_rate
x | [v1.5.2] hiimjustin000.more_icons
x | [v1.0.12] hiimjustin000.more_object_info
  | [v1.1.3] hiimjustin000.requested_ratings
x | [v1.2.0] hjfod.backups
x | [v6.10.0-alpha.3] hjfod.betteredit
* | [v1.0.0] hjfod.bettersave_recovery
x | [v1.4.1] hjfod.gdshare
x | [v1.4.1] hjfod.gmd-api
x | [v1.1.0] hjfod.trashcan
* | [v3.0.0] ikszyon.mhrecolor
x | [v1.3.0] itzkiba.better_progression
x | [v1.2.0] jouca.badgesapi
x | [v0.2.1-alpha] kampwski.level_tags
x | [v1.0.0-beta.3] km7dev.betterquests
x | [v1.1.0] km7dev.quests_in_pause_menu
x | [v1.0.5] lilnibblit.chestalert
* | [v1.1.1] limegradient.modprofiles
x | [v1.2.0] m336.autoleaderboard
  | [v1.3.9] m336.levelinfo
x | [v1.1.1] m336.modbadgeinfo
x | [v1.0.1] mariomastr.progress_of_editor_levels
x | [v1.2.3] mat.run-info
x | [v1.1.3] mishpro.comments_in_pause_menu
x | [v1.2.0-beta.2] ml5.shopping-list
x | [v1.5.0] ml5.treasure-checklist
x | [v1.0.1] n.talking-icons
x | [v1.0.6] neonyaa.showgameversion
x | [v2.2.1] omgrod.garage_plus
x | [v1.0.1] raydeeux.revisedlevelcells
x | [v1.1.2] raydeeux_thesillydoggo.decimalpercentages
x | [v1.3.3] raydeeux_thesillydoggo.evenmoreleveltags
x | [v1.0.4] razoom.object_groups
* | [v1.0.0-alpha.2] sabe.persistenceapi
* | [v1.0.1-alpha.3] sabe.platformersaves
x | [v1.0.1] sheepdotcom.leaderboard_in_pause_menu
x | [v1.0.2] sorkopiko.saveretry
x | [v4.2.0-beta.12] spaghettdev.betterinputs
x | [v1.3.0] syzzi.click_between_frames
x | [v1.3.1] techstudent10.attempt_utils
x | [v1.2.1] techstudent10.settings_plus
* | [v1.1.0] thesillydoggo.comment_emojis
* | [v1.0.4] thesillydoggo.icon_kit_switcher
x | [v1.7.6] thesillydoggo.qolmod
  | [v1.0.1] thesillydoggo.retro_edit
  | [v1.2.0] undefined0.icon_ninja
x | [v1.1.2] uproxide.animated_fire
x | [v1.0.3] uproxide.practice_attempts
x | [v1.3.5] uproxide.textures
x | [v1.2.0] weebify.coins_in_pause_menu
x | [v1.1.0] weebify.level_info_in_pause_menu
x | [v1.2.1] weebify.restartbtn
* | [v1.1.1] xanii.youtubers
x | [v2.1.3] zilko.xdbot
x | [v1.0.3] zsa.edit-attempts

**Comment by SomeGDPerson123** [comment]
wait a minute

**Comment by SomeGDPerson123** [comment]
oh im stupid

**Comment by CattoDev** [comment]
This appears to be a QOLMod crash, try disabling it

**Comment by SomeGDPerson123** [comment]
the crash is from the qol mod

**Comment by SomeGDPerson123** [comment]
i cant read

**Comment by SomeGDPerson123** [comment]
worked, thx
